### ISSUE TITLE
use the atexit library to only save the screen at the end of the program

### ISSUE THREAD

**Issue by uniwix** [uniwix/casioplot#26]

**Comment by miguelTorrinhaPereira** [comment]
This would make the saving of  the screen when save_multiple way faster, since it is only saved once instead of being overridden multiple times

**Comment by miguelTorrinhaPereira** [comment]
In that way the Windows could remain Open, but there should be a option to activate that, it could be annoying to have to close the Windows every time you Run the program, specialy if you are developing/testing it.
